export const languages = [
  ["en", "English"],
  ["zh-CN", "简体中文"],
  ["zh-TW", "繁體中文"],
  ["ja", "日本語"],
  ["de", "Deutsch"],
  ["ru", "Русский"],
  ["fr", "Français"],
  ["es", "Español"],
] as const;

export type Language = (typeof languages)[number][0];

type Translation = {
  title: string;
  description: string;
  navFeatures: string;
  navHow: string;
  navPrivacy: string;
  getFlag: string;
  eyebrow: string;
  heroTitle: string;
  heroAccent: string;
  heroIntro: string;
  addChrome: string;
  seeHow: string;
  proof: string[];
  currentWebsite: string;
  serverPathYou: string;
  details: string[][];
  infoStrip: string[];
  whatGet: string;
  sectionTitle: string[];
  sectionIntro: string;
  features: { label: string; title: string; copy: string }[];
  howEyebrow: string;
  howTitle: string;
  howIntro: string;
  steps: { title: string; copy: string }[];
  privacyEyebrow: string;
  privacyTitle: string[];
  privacyCopy: string;
  privacyChecks: string[];
  readPrivacy: string;
  coming: string;
  finalTitle: string;
  finalCopy: string;
  comingSoon: string;
  footerCopy: string;
  footerPrivacy: string;
  dbIpAttribution: string;
};

const en: Translation = {
  title: "IP Flag — Website IP & Server Location",
  description: "See where every website is hosted.",
  navFeatures: "Features", navHow: "How it works", navPrivacy: "Privacy", getFlag: "Get IP Flag",
  eyebrow: "Website server intelligence", heroTitle: "See where every", heroAccent: " website is hosted.",
  heroIntro: "IP Flag adds a country flag to your browser toolbar and reveals the IP, network and location behind any website in one click.",
  addChrome: "Add to Chrome", seeHow: "See how it works", proof: ["No account", "One-click details", "Built for Chrome"],
  currentWebsite: "CURRENT WEBSITE", serverPathYou: "YOU",
  details: [["IP address", "104.20.23.154"], ["Domain", "example.com"], ["ASN", "AS13335"], ["ISP", "Cloudflare"], ["Timezone", "America/Los_Angeles"], ["Coordinates", "37.7749, -122.4194"]],
  infoStrip: ["COUNTRY FLAG", "IP ADDRESS", "ASN", "ISP", "CITY", "TIMEZONE", "SERVER MAP"],
  whatGet: "What you get", sectionTitle: ["One small flag.", "A clearer internet."], sectionIntro: "Understand the infrastructure behind a website without opening developer tools or another tab.",
  features: [
    { label: "Instant signal", title: "The flag is the answer.", copy: "See the server country without opening a panel. IP Flag keeps the signal right in your browser toolbar." },
    { label: "Network context", title: "Look past the domain.", copy: "Open the popup for the resolved IP, ASN, provider, city, timezone and coordinates behind the site." },
    { label: "Geographic view", title: "Put the server on a map.", copy: "Turn raw infrastructure data into a place you can understand at a glance, without leaving the page." },
  ],
  howEyebrow: "How it works", howTitle: "From URL to location, automatically.", howIntro: "Browse normally. IP Flag handles the lookup and keeps the answer close.",
  steps: [{ title: "Open a website", copy: "Visit any regular HTTP or HTTPS page in your browser." }, { title: "Spot the country", copy: "The toolbar icon changes to the server country flag." }, { title: "Open the full picture", copy: "Click once for the IP, network, city, timezone and map." }],
  privacyEyebrow: "Privacy, plainly", privacyTitle: ["Useful context.", "Nothing extra."], privacyCopy: "IP Flag sends the current website hostname to its geolocation service only to resolve the server location. Results are cached in your browser session for speed and cleared when the session ends.", privacyChecks: ["No account or sign-up", "No ads or behavioral profiles", "No selling of user data"], readPrivacy: "Read the privacy policy",
  coming: "Available on Chrome", finalTitle: "Know where the web takes you.", finalCopy: "Install IP Flag from the Chrome Web Store.", comingSoon: "INSTALL FROM THE", footerCopy: "See where every website is hosted.", footerPrivacy: "Privacy", dbIpAttribution: "IP Geolocation by DB-IP",
};

const translations: Record<Language, Translation> = {
  en,
  "zh-CN": {
    ...en, title: "IP Flag — 网站 IP 与服务器位置", description: "一眼查看网站服务器所在国家。", navFeatures: "功能", navHow: "工作原理", navPrivacy: "隐私", getFlag: "获取 IP Flag", eyebrow: "网站服务器信息", heroTitle: "一眼查看每个", heroAccent: "网站托管在哪里。", heroIntro: "IP Flag 将服务器国家国旗放到浏览器工具栏，一键查看网站背后的 IP、网络和位置。", addChrome: "添加到 Chrome", seeHow: "了解工作原理", proof: ["无需账号", "一键查看详情", "为 Chrome 打造"], currentWebsite: "当前网站", serverPathYou: "你", details: [["IP 地址", "104.20.23.154"], ["域名", "example.com"], ["ASN", "AS13335"], ["ISP", "Cloudflare"], ["时区", "America/Los_Angeles"], ["坐标", "37.7749, -122.4194"]], infoStrip: ["国家国旗", "IP 地址", "ASN", "ISP", "城市", "时区", "服务器地图"], whatGet: "你将获得", sectionTitle: ["一面小国旗。", "看清互联网。"], sectionIntro: "无需打开开发者工具或新标签页，也能了解网站背后的基础设施。", features: [{ label: "即时提示", title: "国旗就是答案。", copy: "无需打开面板即可查看服务器国家。IP Flag 将关键信号放在浏览器工具栏。" }, { label: "网络信息", title: "不止域名。", copy: "打开弹窗，查看网站背后的 IP、ASN、服务商、城市、时区和坐标。" }, { label: "地理视图", title: "把服务器放到地图上。", copy: "将基础设施数据变成一眼就能理解的位置，无需离开当前页面。" }], howEyebrow: "工作原理", howTitle: "从网址到位置，全自动完成。", howIntro: "像平常一样浏览，IP Flag 负责查询并把答案放在手边。", steps: [{ title: "打开网站", copy: "在浏览器中访问任意普通 HTTP 或 HTTPS 页面。" }, { title: "查看国家", copy: "工具栏图标会变成服务器所在国家的国旗。" }, { title: "打开完整信息", copy: "点击一次查看 IP、网络、城市、时区和地图。" }], privacyEyebrow: "隐私说明", privacyTitle: ["只提供有用信息。", "没有多余收集。"], privacyCopy: "IP Flag 仅将当前网站主机名发送到地理位置服务，用于解析服务器位置。结果会缓存在浏览器会话中以提升速度，并在会话结束时清除。", privacyChecks: ["无需账号或注册", "无广告或行为画像", "不出售用户数据"], readPrivacy: "阅读隐私政策", coming: "Chrome 现已提供", finalTitle: "知道网络将你带到哪里。", finalCopy: "现在即可从 Chrome 网上应用店安装 IP Flag。", comingSoon: "立即安装", footerCopy: "一眼查看网站服务器所在国家。", footerPrivacy: "隐私政策", dbIpAttribution: "IP 地理位置数据由 DB-IP 提供",
  },
  "zh-TW": {
    ...en, title: "IP Flag — 網站 IP 與伺服器位置", description: "一眼查看網站伺服器所在國家。", navFeatures: "功能", navHow: "運作方式", navPrivacy: "隱私", getFlag: "取得 IP Flag", eyebrow: "網站伺服器資訊", heroTitle: "一眼查看每個", heroAccent: "網站託管在哪裡。", heroIntro: "IP Flag 將伺服器國家旗幟放到瀏覽器工具列，一鍵查看網站背後的 IP、網路與位置。", addChrome: "加入 Chrome", seeHow: "了解運作方式", proof: ["不需帳號", "一鍵查看詳情", "為 Chrome 打造"], currentWebsite: "目前網站", serverPathYou: "你", details: [["IP 位址", "104.20.23.154"], ["網域", "example.com"], ["ASN", "AS13335"], ["ISP", "Cloudflare"], ["時區", "America/Los_Angeles"], ["座標", "37.7749, -122.4194"]], infoStrip: ["國家旗幟", "IP 位址", "ASN", "ISP", "城市", "時區", "伺服器地圖"], whatGet: "你會獲得", sectionTitle: ["一面小旗幟。", "看清網路世界。"], sectionIntro: "不必開啟開發者工具或新分頁，也能了解網站背後的基礎設施。", features: [{ label: "即時提示", title: "旗幟就是答案。", copy: "不必開啟面板即可查看伺服器國家。IP Flag 將關鍵訊號放在瀏覽器工具列。" }, { label: "網路資訊", title: "不只網域。", copy: "開啟彈窗查看網站背後的 IP、ASN、服務商、城市、時區與座標。" }, { label: "地理視圖", title: "把伺服器放到地圖上。", copy: "將基礎設施資料變成一眼就能理解的位置，不必離開目前頁面。" }], howEyebrow: "運作方式", howTitle: "從網址到位置，自動完成。", howIntro: "像平常一樣瀏覽，IP Flag 負責查詢並把答案放在手邊。", steps: [{ title: "開啟網站", copy: "在瀏覽器中造訪任意一般 HTTP 或 HTTPS 頁面。" }, { title: "查看國家", copy: "工具列圖示會變成伺服器所在國家的旗幟。" }, { title: "開啟完整資訊", copy: "點擊一次查看 IP、網路、城市、時區與地圖。" }], privacyEyebrow: "隱私說明", privacyTitle: ["只提供有用資訊。", "沒有多餘收集。"], privacyCopy: "IP Flag 僅將目前網站主機名稱傳送至地理位置服務，用來解析伺服器位置。結果會暫存於瀏覽器工作階段，結束後即清除。", privacyChecks: ["不需帳號或註冊", "無廣告或行為剖析", "不販售使用者資料"], readPrivacy: "閱讀隱私政策", coming: "Chrome 現已提供", finalTitle: "知道網路將你帶到哪裡。", finalCopy: "現在即可從 Chrome 網路商店安裝 IP Flag。", comingSoon: "立即安裝", footerCopy: "一眼查看網站伺服器所在國家。", footerPrivacy: "隱私政策", dbIpAttribution: "IP 地理位置資料由 DB-IP 提供",
  },
  ja: { ...en, title: "IP Flag — ウェブサイトのIPとサーバー所在地", description: "すべてのウェブサイトがどこでホストされているかを見る。", navFeatures: "機能", navHow: "仕組み", navPrivacy: "プライバシー", getFlag: "IP Flagを入手", eyebrow: "ウェブサイトサーバー情報", heroTitle: "すべての", heroAccent: "サイトのホスト場所を確認。", heroIntro: "IP Flagはブラウザのツールバーにサーバーの国旗を表示し、IP、ネットワーク、場所をワンクリックで確認できます。", addChrome: "Chromeに追加", seeHow: "仕組みを見る", proof: ["アカウント不要", "ワンクリック詳細", "Chrome向け"], currentWebsite: "現在のウェブサイト", serverPathYou: "あなた", infoStrip: ["国旗", "IPアドレス", "ASN", "ISP", "都市", "タイムゾーン", "サーバーマップ"], whatGet: "得られる情報", sectionTitle: ["小さな国旗。", "もっと明確なインターネット。"], sectionIntro: "開発者ツールや別タブを開かずに、サイトのインフラを理解できます。", features: [{ label: "瞬時のシグナル", title: "国旗が答えです。", copy: "パネルを開かずにサーバーの国を確認。重要な情報をツールバーに表示します。" }, { label: "ネットワーク情報", title: "ドメインの先へ。", copy: "IP、ASN、プロバイダー、都市、タイムゾーン、座標を確認できます。" }, { label: "地理表示", title: "サーバーを地図に。", copy: "インフラ情報を一目でわかる場所に変換します。" }], howEyebrow: "仕組み", howTitle: "URLから場所まで自動で。", howIntro: "いつも通り閲覧するだけ。IP Flagが検索して答えを近くに表示します。", steps: [{ title: "ウェブサイトを開く", copy: "通常のHTTPまたはHTTPSページにアクセスします。" }, { title: "国を確認", copy: "ツールバーのアイコンがサーバーの国旗に変わります。" }, { title: "詳細を開く", copy: "クリックしてIP、ネットワーク、都市、タイムゾーン、地図を表示します。" }], privacyEyebrow: "プライバシー", privacyTitle: ["役立つ情報だけ。", "余計なものはありません。"], privacyCopy: "IP Flagはサーバーの場所を解決するためだけに現在のホスト名を送信します。結果はセッション中だけキャッシュされ、終了時に消去されます。", privacyChecks: ["アカウント不要", "広告・行動プロファイルなし", "データを販売しない"], readPrivacy: "プライバシーポリシー", coming: "Chromeで利用可能", finalTitle: "ウェブがどこへつなぐかを知る。", finalCopy: "ChromeウェブストアからIP Flagをインストールできます。", comingSoon: "今すぐインストール", footerCopy: "すべてのウェブサイトのホスト場所を見る。", footerPrivacy: "プライバシー", dbIpAttribution: "IP地理情報: DB-IP" },
  de: { ...en, title: "IP Flag — Website-IP und Serverstandort", description: "Sehen Sie, wo jede Website gehostet wird.", navFeatures: "Funktionen", navHow: "So funktioniert es", navPrivacy: "Datenschutz", getFlag: "IP Flag holen", eyebrow: "Website-Serverinformationen", heroTitle: "Sehen Sie, wo jede", heroAccent: "Website gehostet wird.", heroIntro: "IP Flag zeigt die Serverflagge in der Browser-Symbolleiste und verrät IP, Netzwerk und Standort mit einem Klick.", addChrome: "Zu Chrome hinzufügen", seeHow: "So funktioniert es", proof: ["Kein Konto", "Details mit einem Klick", "Für Chrome entwickelt"], currentWebsite: "AKTUELLE WEBSITE", serverPathYou: "SIE", infoStrip: ["LÄNDERFLAGGE", "IP-ADRESSE", "ASN", "ISP", "STADT", "ZEITZONE", "SERVERKARTE"], whatGet: "Das erhalten Sie", sectionTitle: ["Eine kleine Flagge.", "Ein klareres Internet."], sectionIntro: "Verstehen Sie die Infrastruktur einer Website, ohne Entwicklertools oder einen neuen Tab zu öffnen.", features: [{ label: "Sofortsignal", title: "Die Flagge ist die Antwort.", copy: "Sehen Sie das Serverland, ohne ein Panel zu öffnen. Die Information bleibt in Ihrer Symbolleiste." }, { label: "Netzwerkkontext", title: "Mehr als die Domain.", copy: "IP, ASN, Anbieter, Stadt, Zeitzone und Koordinaten auf einen Blick." }, { label: "Geografische Ansicht", title: "Den Server auf der Karte sehen.", copy: "Infrastrukturdaten werden zu einem verständlichen Ort." }], howEyebrow: "So funktioniert es", howTitle: "Von der URL zum Standort – automatisch.", howIntro: "Surfen Sie normal. IP Flag übernimmt die Suche und hält die Antwort bereit.", steps: [{ title: "Website öffnen", copy: "Besuchen Sie eine normale HTTP- oder HTTPS-Seite." }, { title: "Land erkennen", copy: "Das Symbol zeigt die Flagge des Serverlandes." }, { title: "Details öffnen", copy: "IP, Netzwerk, Stadt, Zeitzone und Karte mit einem Klick." }], privacyEyebrow: "Datenschutz, klar erklärt", privacyTitle: ["Nützlicher Kontext.", "Nichts weiter."], privacyCopy: "IP Flag sendet den Hostnamen nur zur Ermittlung des Serverstandorts an den Geodienst. Ergebnisse werden nur während der Sitzung zwischengespeichert.", privacyChecks: ["Kein Konto erforderlich", "Keine Werbung oder Profile", "Keine Weitergabe von Daten"], readPrivacy: "Datenschutzerklärung", coming: "Jetzt in Chrome verfügbar", finalTitle: "Wissen, wohin das Web führt.", finalCopy: "Installieren Sie IP Flag jetzt aus dem Chrome Web Store.", comingSoon: "JETZT INSTALLIEREN", footerCopy: "Sehen Sie, wo jede Website gehostet wird.", footerPrivacy: "Datenschutz", dbIpAttribution: "IP-Geodaten von DB-IP" },
  ru: { ...en, title: "IP Flag — IP и расположение сервера сайта", description: "Узнайте, где размещён любой сайт.", navFeatures: "Возможности", navHow: "Как это работает", navPrivacy: "Конфиденциальность", getFlag: "Получить IP Flag", eyebrow: "Данные сервера сайта", heroTitle: "Узнайте, где размещён", heroAccent: "любой сайт.", heroIntro: "IP Flag показывает флаг страны сервера в панели браузера и одним нажатием раскрывает IP, сеть и местоположение.", addChrome: "Добавить в Chrome", seeHow: "Как это работает", proof: ["Без аккаунта", "Детали одним нажатием", "Создано для Chrome"], currentWebsite: "ТЕКУЩИЙ САЙТ", serverPathYou: "ВЫ", infoStrip: ["ФЛАГ СТРАНЫ", "IP-АДРЕС", "ASN", "ISP", "ГОРОД", "ЧАСОВОЙ ПОЯС", "КАРТА СЕРВЕРА"], whatGet: "Что вы получаете", sectionTitle: ["Один маленький флаг.", "Более понятный интернет."], sectionIntro: "Понимайте инфраструктуру сайта без инструментов разработчика и новых вкладок.", features: [{ label: "Мгновенный сигнал", title: "Флаг — это ответ.", copy: "Узнайте страну сервера, не открывая панель. Сигнал всегда рядом в браузере." }, { label: "Сетевой контекст", title: "Смотрите дальше домена.", copy: "IP, ASN, провайдер, город, часовой пояс и координаты сайта." }, { label: "Географический вид", title: "Поместите сервер на карту.", copy: "Превратите данные инфраструктуры в понятное место." }], howEyebrow: "Как это работает", howTitle: "От URL к местоположению автоматически.", howIntro: "Просто просматривайте сайты. IP Flag сам выполнит поиск.", steps: [{ title: "Откройте сайт", copy: "Перейдите на обычную страницу HTTP или HTTPS." }, { title: "Посмотрите страну", copy: "Иконка панели изменится на флаг страны сервера." }, { title: "Откройте детали", copy: "Одно нажатие покажет IP, сеть, город, часовой пояс и карту." }], privacyEyebrow: "О конфиденциальности", privacyTitle: ["Только полезный контекст.", "Ничего лишнего."], privacyCopy: "IP Flag отправляет имя текущего хоста только для определения местоположения сервера. Результаты кэшируются в сессии и удаляются после её завершения.", privacyChecks: ["Без аккаунта", "Без рекламы и профилей", "Без продажи данных"], readPrivacy: "Политика конфиденциальности", coming: "Доступно в Chrome", finalTitle: "Знайте, куда ведёт интернет.", finalCopy: "Установите IP Flag из Chrome Web Store.", comingSoon: "УСТАНОВИТЬ", footerCopy: "Узнайте, где размещён любой сайт.", footerPrivacy: "Конфиденциальность", dbIpAttribution: "Геоданные IP от DB-IP" },
  fr: { ...en, title: "IP Flag — IP et emplacement du serveur", description: "Découvrez où chaque site est hébergé.", navFeatures: "Fonctionnalités", navHow: "Fonctionnement", navPrivacy: "Confidentialité", getFlag: "Obtenir IP Flag", eyebrow: "Informations du serveur", heroTitle: "Découvrez où chaque", heroAccent: "site est hébergé.", heroIntro: "IP Flag affiche le drapeau du pays du serveur dans la barre du navigateur et révèle IP, réseau et emplacement en un clic.", addChrome: "Ajouter à Chrome", seeHow: "Voir le fonctionnement", proof: ["Sans compte", "Détails en un clic", "Conçu pour Chrome"], currentWebsite: "SITE ACTUEL", serverPathYou: "VOUS", infoStrip: ["DRAPEAU", "ADRESSE IP", "ASN", "FAI", "VILLE", "FUSEAU HORAIRE", "CARTE DU SERVEUR"], whatGet: "Ce que vous obtenez", sectionTitle: ["Un petit drapeau.", "Un Internet plus clair."], sectionIntro: "Comprenez l’infrastructure d’un site sans ouvrir les outils de développement ni un autre onglet.", features: [{ label: "Signal instantané", title: "Le drapeau est la réponse.", copy: "Voyez le pays du serveur sans ouvrir de panneau. Le signal reste dans votre barre d’outils." }, { label: "Contexte réseau", title: "Au-delà du domaine.", copy: "IP, ASN, fournisseur, ville, fuseau horaire et coordonnées en un coup d’œil." }, { label: "Vue géographique", title: "Placez le serveur sur une carte.", copy: "Transformez les données d’infrastructure en un lieu compréhensible." }], howEyebrow: "Fonctionnement", howTitle: "De l’URL à l’emplacement, automatiquement.", howIntro: "Naviguez normalement. IP Flag s’occupe de la recherche.", steps: [{ title: "Ouvrir un site", copy: "Visitez une page HTTP ou HTTPS classique." }, { title: "Repérer le pays", copy: "L’icône affiche le drapeau du pays du serveur." }, { title: "Voir les détails", copy: "Un clic pour l’IP, le réseau, la ville, le fuseau et la carte." }], privacyEyebrow: "La confidentialité, simplement", privacyTitle: ["Un contexte utile.", "Rien de plus."], privacyCopy: "IP Flag envoie le nom d’hôte uniquement pour déterminer l’emplacement du serveur. Les résultats sont conservés pendant la session puis supprimés.", privacyChecks: ["Aucun compte", "Aucune publicité ni profil", "Aucune vente de données"], readPrivacy: "Lire la politique de confidentialité", coming: "Bientôt sur Chrome", finalTitle: "Sachez où le web vous mène.", finalCopy: "IP Flag prépare son arrivée sur le Chrome Web Store.", comingSoon: "BIENTÔT", footerCopy: "Découvrez où chaque site est hébergé.", footerPrivacy: "Confidentialité", dbIpAttribution: "Données IP par DB-IP" },
  es: { ...en, title: "IP Flag — IP y ubicación del servidor", description: "Descubre dónde está alojado cada sitio web.", navFeatures: "Funciones", navHow: "Cómo funciona", navPrivacy: "Privacidad", getFlag: "Obtener IP Flag", eyebrow: "Información del servidor", heroTitle: "Descubre dónde está alojado", heroAccent: "cada sitio web.", heroIntro: "IP Flag muestra la bandera del país del servidor en la barra del navegador y revela IP, red y ubicación con un clic.", addChrome: "Añadir a Chrome", seeHow: "Ver cómo funciona", proof: ["Sin cuenta", "Detalles con un clic", "Creado para Chrome"], currentWebsite: "SITIO ACTUAL", serverPathYou: "TÚ", infoStrip: ["BANDERA", "DIRECCIÓN IP", "ASN", "ISP", "CIUDAD", "ZONA HORARIA", "MAPA DEL SERVIDOR"], whatGet: "Lo que obtienes", sectionTitle: ["Una bandera pequeña.", "Un internet más claro."], sectionIntro: "Entiende la infraestructura de un sitio sin abrir las herramientas de desarrollo ni otra pestaña.", features: [{ label: "Señal instantánea", title: "La bandera es la respuesta.", copy: "Consulta el país del servidor sin abrir un panel. La señal queda en tu barra de herramientas." }, { label: "Contexto de red", title: "Más allá del dominio.", copy: "Consulta IP, ASN, proveedor, ciudad, zona horaria y coordenadas." }, { label: "Vista geográfica", title: "Pon el servidor en el mapa.", copy: "Convierte los datos de infraestructura en un lugar fácil de entender." }], howEyebrow: "Cómo funciona", howTitle: "De la URL a la ubicación, automáticamente.", howIntro: "Navega con normalidad. IP Flag se encarga de la consulta.", steps: [{ title: "Abre un sitio", copy: "Visita cualquier página HTTP o HTTPS normal." }, { title: "Mira el país", copy: "El icono muestra la bandera del país del servidor." }, { title: "Abre todos los datos", copy: "Un clic para ver IP, red, ciudad, zona horaria y mapa." }], privacyEyebrow: "Privacidad, sin rodeos", privacyTitle: ["Contexto útil.", "Nada más."], privacyCopy: "IP Flag envía el nombre de host actual solo para resolver la ubicación del servidor. Los resultados se guardan durante la sesión y se eliminan al terminar.", privacyChecks: ["Sin cuenta", "Sin anuncios ni perfiles", "Sin venta de datos"], readPrivacy: "Leer la política de privacidad", coming: "Próximamente en Chrome", finalTitle: "Sabe adónde te lleva la web.", finalCopy: "IP Flag se prepara para llegar a Chrome Web Store.", comingSoon: "PRÓXIMAMENTE", footerCopy: "Descubre dónde está alojado cada sitio web.", footerPrivacy: "Privacidad", dbIpAttribution: "Datos de IP por DB-IP" },
};

translations.de = { ...translations.de, coming: "Jetzt in Chrome verfügbar", finalCopy: "Installieren Sie IP Flag jetzt aus dem Chrome Web Store.", comingSoon: "JETZT INSTALLIEREN" };
translations.ru = { ...translations.ru, coming: "Доступно в Chrome", finalCopy: "Установите IP Flag из Chrome Web Store.", comingSoon: "УСТАНОВИТЬ" };
translations.fr = { ...translations.fr, coming: "Disponible sur Chrome", finalCopy: "Installez IP Flag depuis le Chrome Web Store.", comingSoon: "INSTALLER" };
translations.es = { ...translations.es, coming: "Disponible en Chrome", finalCopy: "Instala IP Flag desde Chrome Web Store.", comingSoon: "INSTALAR" };

export function getTranslation(language: Language) {
  return translations[language] || en;
}
